version: '3'
services:
  db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
      - 7473:7473
    volumes:
      - ./db/dbms:/data/dbms
      - ./db/plugins:/plugins
      - ./db/conf:/conf

  backend:
    build:
      context: .
      dockerfile: ./compose/nodejs/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
    links:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ./compose/react/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    env_file:
      - .env
