version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:9.3.0
    working_directory: ~/dataportal

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            yarn install

      - run:
          name: Run ESlint
          command: |
            yarn eslint src/components/
            yarn eslint src/containers/
 
      - run:
          name: Run Unit Tests
          command: yarn test src/components/__tests__/EditDatabaseSource.test.js --bail --ci
            
